import type { Metadata } from "next";
import { Barlow_Condensed, Geist, Geist_Mono } from "next/font/google";
import User from "./components/user";
import Brand from "./components/brand";
import NavigationIsland from "./components/navigationIsland";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-black bg-zinc-50`}>
          {/* Stationary items like user profile and brand name */}
          <div className="absolute top-0 flex justify-between items-center w-full px-4 py-2">
            <Brand name={"Ikeddi"} />
            <User />
          </div>
          <NavigationIsland />
          {children}
      </body>
    </html>
  );
}
